name: Testing self-hosted runner (New ARC Runner)


on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: arc-runner-set-big
    steps:
    - name: Know the env
      run: |
        pwd
        ls
        env
    - name: Hello world
      run: echo "Hello World"
    - name: Will just sleep for a minute
      run: sleep 120
    - name: Goodbye
      run: echo "Goodbye"
