name: Build and push Artifacts

on:
  workflow_call:
    secrets:
      DUSERNAME:
        required: true
      DPASSWORD:
        required: true
    inputs:
      docker_repo:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Build docker image
      run: docker build -t ${{ inputs.docker_repo }}:latest .

    - name: Login to docker
      run: docker login -u ${{ secrets.DUSERNAME }} -p ${{ secrets.DPASSWORD }}

    - name: Push the image to docker registry
      run: docker push ${{ inputs.docker_repo }}:latest 
    
    - name: Build helm chart
      run: helm package charts/spring-boot-hello-world
    
    - name: Move helm chart to charts
      run: mv spring-boot-hello-world-0.1.0.tgz charts/

    - name: Generate the index.yaml
      run: helm repo charts/index --url https://rahulkausale.github.io/spring-boot-hello-world/charts/ .

    # - name: Push the helm chart
    #   run: git add charts/ && git commit -m "Pushing chart" && git push

    - uses: stefanzweifel/git-auto-commit-action@v5
  